//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADModel : DbContext
    {
        public DADModel()
            : base("name=DADModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers102146016> Customers102146016 { get; set; }
        public virtual DbSet<Interests102146016> Interests102146016 { get; set; }
        public virtual DbSet<Orders102146016> Orders102146016 { get; set; }
        public virtual DbSet<Perform102146016> Perform102146016 { get; set; }
    }
}
