//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interests102146016
    {
        public string InterestCode { get; set; }
        public int CustomerNo { get; set; }
        public string InterestDesc { get; set; }
    
        public virtual Customers102146016 Customers102146016 { get; set; }
    }
}
