//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders102146016
    {
        public int CustomerNo { get; set; }
        public string RecordID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Customers102146016 Customers102146016 { get; set; }
        public virtual Perform102146016 Perform102146016 { get; set; }
    }
}
